[project]
name = "PatternLanguage"
msvc-runtime = "static"
cmake-after = """
if(CMAKE_CXX_COMPILER_ID MATCHES \"Clang\" AND CMAKE_SIZEOF_VOID_P EQUAL 4)
    add_compile_definitions(FMT_USE_CONSTEVAL=0)
endif()
"""

[fetch-content.PatternLanguage]
git = "https://github.com/WerWolv/PatternLanguage"
tag = "a9a93ab56b7808cb5d551ff94d7bad8a3c963618"

[options]
LIBPL_ENABLE_CLI = false

[target.PatternLanguage]
type = "shared"
sources = [
    "src/PatternLanguage.cpp",
    "src/PatternLanguage.h",
]
link-libraries = [
    "::libpl",
    "::libpl-gen",
    "fmt::fmt-header-only",
]
compile-features = ["cxx_std_23"]

[target.PatternLanguage.properties]
OUTPUT_NAME = "PatternLanguage"
PREFIX = ""
IMPORT_PREFIX = ""

[target.example]
type = "executable"
sources = ["src/example.cpp"]
link-libraries = ["::PatternLanguage"]
